const courses = [
  { name: 'Medicine & Surgery', combinations: ['Biology', 'Chemistry', 'Physics'] },
  { name: 'Dentistry', combinations: ['Biology', 'Chemistry', 'Physics'] },
  { name: 'Veterinary Medicine', combinations: ['Biology', 'Chemistry', 'Physics'] },
  { name: 'Pharmacy', combinations: ['Chemistry', 'Biology', 'Physics'] },
  { name: 'Nursing', combinations: ['Biology', 'Chemistry', 'Physics'] },
  { name: 'Public Health', combinations: ['Biology', 'Chemistry', 'Economics'] },
  { name: 'Medical Laboratory Science', combinations: ['Chemistry', 'Biology', 'Physics'] },
  { name: 'Physiotherapy', combinations: ['Biology', 'Chemistry', 'Physics'] },
  { name: 'Law', combinations: ['Government', 'Economics', 'History'] },
  { name: 'Computer Science', combinations: ['Mathematics', 'Physics', 'Chemistry'] },
  { name: 'Information Technology', combinations: ['Mathematics', 'Physics', 'Chemistry'] },
  { name: 'Software Engineering', combinations: ['Mathematics', 'Physics', 'Chemistry'] },
  { name: 'Electrical Engineering', combinations: ['Mathematics', 'Physics', 'Chemistry'] },
  { name: 'Civil Engineering', combinations: ['Mathematics', 'Physics', 'Chemistry'] },
  { name: 'Mechanical Engineering', combinations: ['Mathematics', 'Physics', 'Chemistry'] },
  { name: 'Chemical Engineering', combinations: ['Chemistry', 'Physics', 'Mathematics'] },
  { name: 'Agricultural Engineering', combinations: ['Agriculture', 'Physics', 'Chemistry'] },
  { name: 'Architecture', combinations: ['Mathematics', 'Physics', 'Chemistry'] },
  { name: 'Urban & Regional Planning', combinations: ['Geography', 'Government', 'Mathematics'] },
  { name: 'Economics', combinations: ['Mathematics', 'Economics', 'Government'] },
  { name: 'Accounting', combinations: ['Mathematics', 'Economics', 'Commerce'] },
  { name: 'Business Administration', combinations: ['Economics', 'Mathematics', 'Government'] },
  { name: 'Banking & Finance', combinations: ['Mathematics', 'Economics', 'Commerce'] },
  { name: 'Marketing', combinations: ['Economics', 'Government', 'Commerce'] },
  { name: 'Management Sciences', combinations: ['Mathematics', 'Economics', 'Government'] },
  { name: 'Physics', combinations: ['Mathematics', 'Chemistry', 'Physics'] },
  { name: 'Chemistry', combinations: ['Mathematics', 'Chemistry', 'Biology'] },
  { name: 'Biology', combinations: ['Chemistry', 'Biology', 'Physics'] },
  { name: 'Botany', combinations: ['Biology', 'Chemistry', 'Physics'] },
  { name: 'Zoology', combinations: ['Biology', 'Chemistry', 'Physics'] },
  { name: 'Mathematics', combinations: ['Physics', 'Chemistry', 'Further Mathematics'] },
  { name: 'Statistics', combinations: ['Mathematics', 'Economics', 'Government'] },
  { name: 'Geology', combinations: ['Geography', 'Chemistry', 'Physics'] },
  { name: 'Geography', combinations: ['Geography', 'Economics', 'Government'] },
  { name: 'History', combinations: ['History', 'Government', 'Economics'] },
  { name: 'International Relations', combinations: ['Government', 'History', 'Economics'] },
  { name: 'Education', combinations: ['Education', 'Government', 'Economics'] },
  { name: 'Psychology', combinations: ['Biology', 'Chemistry', 'Government'] },
  { name: 'Sociology', combinations: ['Government', 'Economics', 'History'] },
  {
    name: 'Literature-in-English',
    combinations: ['Literature-in-English', 'History', 'Government'],
  },
  { name: 'English Language', combinations: ['Economics', 'Government', 'History'] },
  { name: 'Fine Arts', combinations: ['History', 'Government', 'Geography'] },
  { name: 'Music', combinations: ['History', 'Government', 'Geography'] },
  { name: 'Theatre Arts', combinations: ['History', 'Literature-in-English', 'Government'] },
  { name: 'Philosophy', combinations: ['History', 'Government', 'CRS'] },
  { name: 'Religious Studies', combinations: ['CRS', 'Government', 'History'] },
  { name: 'Islamic Studies', combinations: ['IRS', 'Government', 'History'] },
  { name: 'Agriculture', combinations: ['Agriculture', 'Biology', 'Chemistry'] },
  { name: 'Animal Science', combinations: ['Agriculture', 'Biology', 'Chemistry'] },
  { name: 'Food Science & Technology', combinations: ['Chemistry', 'Biology', 'Agriculture'] },
  { name: 'Soil Science', combinations: ['Agriculture', 'Chemistry', 'Geography'] },
  { name: 'Forestry', combinations: ['Agriculture', 'Biology', 'Geography'] },
  { name: 'Nursing Science', combinations: ['Biology', 'Chemistry', 'Physics'] },
  { name: 'Environmental Science', combinations: ['Biology', 'Chemistry', 'Geography'] },
  { name: 'Microbiology', combinations: ['Biology', 'Chemistry', 'Physics'] },
  { name: 'Biochemistry', combinations: ['Chemistry', 'Biology', 'Physics'] },
];

// Note: "Use of English" is always compulsory and added automatically as the first subject

module.exports = courses;
