const db = require('../backend/config/db');
const bcrypt = require('bcryptjs');

const subjects = [
  { name: 'Use of English', code: 'USE_OF_ENGLISH', duration: 60, isCompulsory: 1 },
  { name: 'Mathematics', code: 'MATHEMATICS', duration: 120, isCompulsory: 0 },
  { name: 'Physics', code: 'PHYSICS', duration: 120, isCompulsory: 0 },
  { name: 'Chemistry', code: 'CHEMISTRY', duration: 120, isCompulsory: 0 },
  { name: 'Biology', code: 'BIOLOGY', duration: 120, isCompulsory: 0 },
  { name: 'Economics', code: 'ECONOMICS', duration: 60, isCompulsory: 0 },
  { name: 'Government', code: 'GOVERNMENT', duration: 60, isCompulsory: 0 },
  { name: 'Literature-in-English', code: 'LITERATURE', duration: 60, isCompulsory: 0 },
  { name: 'Geography', code: 'GEOGRAPHY', duration: 60, isCompulsory: 0 },
  { name: 'Agriculture', code: 'AGRICULTURE', duration: 60, isCompulsory: 0 },
  { name: 'Commerce', code: 'COMMERCE', duration: 60, isCompulsory: 0 },
  { name: 'Accounting', code: 'ACCOUNTING', duration: 60, isCompulsory: 0 },
  { name: 'CRS', code: 'CRS', duration: 60, isCompulsory: 0 },
  { name: 'IRS', code: 'IRS', duration: 60, isCompulsory: 0 },
];

// 40 USE OF ENGLISH questions
const englishQuestions = [
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'Which of the following is an abstract noun?',
    choices: JSON.stringify(['car', 'beauty', 'apple', 'chair']),
    answer: 'beauty',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: "The manager was responsible _____ the project's success.",
    choices: JSON.stringify(['on', 'for', 'in', 'at']),
    answer: 'for',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'She _____ to the market every day.',
    choices: JSON.stringify(['go', 'goes', 'going', 'gone']),
    answer: 'goes',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'Neither the teacher nor the students _____ ready for the exam.',
    choices: JSON.stringify(['is', 'are', 'was', 'were']),
    answer: 'are',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'If I _____ known the truth, I would have told you.',
    choices: JSON.stringify(['had', 'have', 'would', 'could']),
    answer: 'had',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'The _____ of the play was outstanding.',
    choices: JSON.stringify(['act', 'scene', 'performance', 'actor']),
    answer: 'performance',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'His _____ remarks offended everyone at the meeting.',
    choices: JSON.stringify(['tactful', 'tactless', 'tact', 'tactics']),
    answer: 'tactless',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'The committee _____ divided on the issue.',
    choices: JSON.stringify(['is', 'are', 'was', 'were']),
    answer: 'is',
    year: 2022,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Comprehension',
    questionText: 'What does "ephemeral" mean?',
    choices: JSON.stringify(['lasting', 'short-lived', 'permanent', 'eternal']),
    answer: 'short-lived',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'Despite his illness, he _____ to work.',
    choices: JSON.stringify(['go', 'goes', 'went', 'gone']),
    answer: 'went',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'The student showed great _____ in solving the problem.',
    choices: JSON.stringify(['acuity', 'acidity', 'activity', 'actuality']),
    answer: 'acuity',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'I suggest that he _____ more attention to his studies.',
    choices: JSON.stringify(['pay', 'pays', 'paid', 'would pay']),
    answer: 'pay',
    year: 2022,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'Her _____ to help others is admirable.',
    choices: JSON.stringify(['propensity', 'property', 'prosperity', 'propriety']),
    answer: 'propensity',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'Either you or I _____ to go there.',
    choices: JSON.stringify(['have', 'has', 'am', 'is']),
    answer: 'have',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Comprehension',
    questionText: 'What is a synonym for "benevolent"?',
    choices: JSON.stringify(['cruel', 'kind', 'angry', 'sad']),
    answer: 'kind',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'The number of students _____ increased this year.',
    choices: JSON.stringify(['have', 'has', 'are', 'is']),
    answer: 'has',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'His _____ behavior made him unpopular.',
    choices: JSON.stringify(['gregarious', 'garrulous', 'gullible', 'gregarious']),
    answer: 'garrulous',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'I wish I _____ taller.',
    choices: JSON.stringify(['am', 'was', 'were', 'be']),
    answer: 'were',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Comprehension',
    questionText: 'What does "assiduous" mean?',
    choices: JSON.stringify(['lazy', 'diligent', 'careless', 'bold']),
    answer: 'diligent',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'She has lived here _____ five years.',
    choices: JSON.stringify(['since', 'for', 'during', 'while']),
    answer: 'for',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'The _____ of the building was impressive.',
    choices: JSON.stringify(['architecture', 'architect', 'architectural', 'architrave']),
    answer: 'architecture',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'If you study hard, you _____ pass the exam.',
    choices: JSON.stringify(['will', 'would', 'shall', 'should']),
    answer: 'will',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Comprehension',
    questionText: 'What is an antonym for "verbose"?',
    choices: JSON.stringify(['talkative', 'concise', 'loud', 'quiet']),
    answer: 'concise',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'The girl _____ her homework when the lights went out.',
    choices: JSON.stringify(['does', 'did', 'was doing', 'has done']),
    answer: 'was doing',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'His _____ comment broke the ice at the party.',
    choices: JSON.stringify(['acerbic', 'acrid', 'acidic', 'acute']),
    answer: 'acerbic',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'I would have attended if I _____ known about it.',
    choices: JSON.stringify(['have', 'had', 'would', 'could']),
    answer: 'had',
    year: 2022,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Comprehension',
    questionText: 'Which word means "excessively wordy"?',
    choices: JSON.stringify(['succinct', 'verbose', 'brief', 'terse']),
    answer: 'verbose',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'The team _____ won the championship last year.',
    choices: JSON.stringify(['who', 'which', 'that', 'whose']),
    answer: 'that',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'The patient showed signs of _____ improvement.',
    choices: JSON.stringify(['marred', 'marked', 'masked', 'massed']),
    answer: 'marked',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'None of the students _____ ready for the test.',
    choices: JSON.stringify(['is', 'are', 'was', 'were']),
    answer: 'are',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Comprehension',
    questionText: 'What does "aesthetic" refer to?',
    choices: JSON.stringify(['science', 'beauty', 'math', 'history']),
    answer: 'beauty',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'He insisted _____ his innocence.',
    choices: JSON.stringify(['in', 'on', 'at', 'for']),
    answer: 'on',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'The _____ of the project led to its success.',
    choices: JSON.stringify(['conception', 'conception', 'consummation', 'consumption']),
    answer: 'conception',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'I am afraid _____ failing the exam.',
    choices: JSON.stringify(['of', 'about', 'from', 'for']),
    answer: 'of',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Use of English',
    topic: 'Comprehension',
    questionText: 'An "esoteric" meaning is:',
    choices: JSON.stringify(['common', 'understood by few', 'popular', 'simple']),
    answer: 'understood by few',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'She is not only intelligent but _____ hardworking.',
    choices: JSON.stringify(['also', 'moreover', 'furthermore', 'besides']),
    answer: 'also',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Use of English',
    topic: 'Vocabulary',
    questionText: 'His _____ lifestyle annoyed his neighbors.',
    choices: JSON.stringify(['abstemious', 'abstinent', 'obsequious', 'ostentatious']),
    answer: 'ostentatious',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'The film _____ by a renowned director won several awards.',
    choices: JSON.stringify(['directed', 'directing', 'having directed', 'to direct']),
    answer: 'directed',
    year: 2022,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Comprehension',
    questionText: 'What does "cacophony" mean?',
    choices: JSON.stringify(['harmony', 'discord', 'silence', 'music']),
    answer: 'discord',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Use of English',
    topic: 'Grammar',
    questionText: 'By the time you arrive, I _____ dinner.',
    choices: JSON.stringify(['cook', 'will cook', 'will have cooked', 'am cooking']),
    answer: 'will have cooked',
    year: 2022,
    difficulty: 'hard',
  },
];

// 30 MATHEMATICS questions
const mathQuestions = [
  {
    subject: 'Mathematics',
    topic: 'Arithmetic',
    questionText: 'What is 7 × 8?',
    choices: JSON.stringify(['54', '56', '58', '64']),
    answer: '56',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Geometry',
    questionText: 'Find the area of a circle with radius 7cm (use π = 22/7)',
    choices: JSON.stringify(['154 cm²', '308 cm²', '44 cm²', '88 cm²']),
    answer: '154 cm²',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'What is the value of x if 2x + 5 = 15?',
    choices: JSON.stringify(['5', '10', '15', '20']),
    answer: '5',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    questionText: 'What is sin(90°)?',
    choices: JSON.stringify(['0', '0.5', '1', '-1']),
    answer: '1',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'Solve: x² - 5x + 6 = 0',
    choices: JSON.stringify(['x = 2 or 3', 'x = -2 or -3', 'x = 1 or 6', 'x = 0 or 5']),
    answer: 'x = 2 or 3',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Mathematics',
    topic: 'Geometry',
    questionText: 'What is the sum of angles in a triangle?',
    choices: JSON.stringify(['90°', '180°', '270°', '360°']),
    answer: '180°',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Arithmetic',
    questionText: 'What is 15% of 200?',
    choices: JSON.stringify(['15', '30', '45', '60']),
    answer: '30',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Statistics',
    questionText: 'What is the mean of 2, 4, 6, 8, 10?',
    choices: JSON.stringify(['4', '6', '8', '10']),
    answer: '6',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'If a = 3 and b = 4, what is a² + b²?',
    choices: JSON.stringify(['7', '12', '25', '49']),
    answer: '25',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Geometry',
    questionText: 'What is the perimeter of a square with side 5cm?',
    choices: JSON.stringify(['10 cm', '15 cm', '20 cm', '25 cm']),
    answer: '20 cm',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    questionText: 'What is cos(0°)?',
    choices: JSON.stringify(['0', '0.5', '1', '-1']),
    answer: '1',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'Simplify: 3x + 2x - x',
    choices: JSON.stringify(['4x', '5x', '3x', '2x']),
    answer: '4x',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Geometry',
    questionText: 'How many sides does a hexagon have?',
    choices: JSON.stringify(['4', '5', '6', '7']),
    answer: '6',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Arithmetic',
    questionText: 'What is ½ + ¼?',
    choices: JSON.stringify(['⅙', '⅜', '¾', '⅞']),
    answer: '¾',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'What is the value of 2³?',
    choices: JSON.stringify(['6', '8', '9', '12']),
    answer: '8',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Statistics',
    questionText: 'What is the median of 1, 2, 3, 4, 5?',
    choices: JSON.stringify(['1', '2', '3', '4']),
    answer: '3',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Geometry',
    questionText: 'What is the circumference of a circle with radius 3.5cm? (π = 22/7)',
    choices: JSON.stringify(['11 cm', '22 cm', '33 cm', '44 cm']),
    answer: '22 cm',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'Solve: 3(x - 2) = 9',
    choices: JSON.stringify(['1', '3', '5', '7']),
    answer: '5',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    questionText: 'What is tan(45°)?',
    choices: JSON.stringify(['0', '0.5', '1', '√2']),
    answer: '1',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Mathematics',
    topic: 'Geometry',
    questionText: 'What is the volume of a cube with side 3cm?',
    choices: JSON.stringify(['9 cm³', '18 cm³', '27 cm³', '36 cm³']),
    answer: '27 cm³',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Mathematics',
    topic: 'Arithmetic',
    questionText: 'What is 20% of 150?',
    choices: JSON.stringify(['20', '30', '40', '50']),
    answer: '30',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'If 3x = 18, what is x?',
    choices: JSON.stringify(['3', '6', '9', '12']),
    answer: '6',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Geometry',
    questionText: 'What is the area of a rectangle with length 8cm and width 5cm?',
    choices: JSON.stringify(['13 cm²', '26 cm²', '40 cm²', '80 cm²']),
    answer: '40 cm²',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Statistics',
    questionText: 'What is the range of 2, 5, 8, 12, 3?',
    choices: JSON.stringify(['3', '7', '10', '12']),
    answer: '10',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'What is the GCF of 12 and 18?',
    choices: JSON.stringify(['2', '3', '6', '12']),
    answer: '6',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Trigonometry',
    questionText: 'What is sin(0°)?',
    choices: JSON.stringify(['0', '0.5', '1', '-1']),
    answer: '0',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Geometry',
    questionText: 'How many degrees are in a straight line?',
    choices: JSON.stringify(['90°', '180°', '270°', '360°']),
    answer: '180°',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'What is the LCM of 4 and 6?',
    choices: JSON.stringify(['12', '10', '8', '24']),
    answer: '12',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Mathematics',
    topic: 'Geometry',
    questionText: 'What is the diagonal of a square with side 4cm?',
    choices: JSON.stringify(['4 cm', '4√2 cm', '8 cm', '8√2 cm']),
    answer: '4√2 cm',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Mathematics',
    topic: 'Algebra',
    questionText: 'Solve: x/2 + 3 = 8',
    choices: JSON.stringify(['5', '10', '15', '20']),
    answer: '10',
    year: 2022,
    difficulty: 'medium',
  },
];

// 20 PHYSICS questions
const physicsQuestions = [
  {
    subject: 'Physics',
    topic: 'Mechanics',
    questionText: 'What is the SI unit of force?',
    choices: JSON.stringify(['Joule', 'Newton', 'Watt', 'Pascal']),
    answer: 'Newton',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Mechanics',
    questionText: 'Define acceleration.',
    choices: JSON.stringify([
      'Speed at a moment',
      'Rate of change of velocity',
      'Distance covered',
      'Total distance',
    ]),
    answer: 'Rate of change of velocity',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Thermodynamics',
    questionText: 'What is the SI unit of temperature?',
    choices: JSON.stringify(['Celsius', 'Fahrenheit', 'Kelvin', 'Rankine']),
    answer: 'Kelvin',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Waves',
    questionText: 'What is the speed of light in vacuum?',
    choices: JSON.stringify(['3 × 10⁸ m/s', '3 × 10⁹ m/s', '3 × 10⁷ m/s', '3 × 10¹⁰ m/s']),
    answer: '3 × 10⁸ m/s',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Electricity',
    questionText: 'What is the SI unit of current?',
    choices: JSON.stringify(['Volt', 'Ampere', 'Ohm', 'Coulomb']),
    answer: 'Ampere',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Mechanics',
    questionText: "What does Newton's first law state?",
    choices: JSON.stringify([
      'Force = mass × acceleration',
      'Action = Reaction',
      'Objects at rest stay at rest',
      'Energy is conserved',
    ]),
    answer: 'Objects at rest stay at rest',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Physics',
    topic: 'Electricity',
    questionText: 'What is the SI unit of resistance?',
    choices: JSON.stringify(['Ampere', 'Volt', 'Ohm', 'Watt']),
    answer: 'Ohm',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Thermodynamics',
    questionText: 'What is absolute zero in Celsius?',
    choices: JSON.stringify(['-273.15°C', '-100°C', '0°C', '-373.15°C']),
    answer: '-273.15°C',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Physics',
    topic: 'Waves',
    questionText: 'What is the SI unit of frequency?',
    choices: JSON.stringify(['Hz', 'rad/s', 's', 'm']),
    answer: 'Hz',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Mechanics',
    questionText: 'What is momentum?',
    choices: JSON.stringify([
      'Force × time',
      'Mass × velocity',
      'Energy × time',
      'Distance × mass',
    ]),
    answer: 'Mass × velocity',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Electricity',
    questionText: 'What is the SI unit of power?',
    choices: JSON.stringify(['Joule', 'Newton', 'Watt', 'Volt']),
    answer: 'Watt',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Optics',
    questionText: 'What is the angle of incidence equal to?',
    choices: JSON.stringify([
      'Angle of refraction',
      'Angle of reflection',
      'Critical angle',
      "Brewster's angle",
    ]),
    answer: 'Angle of reflection',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Physics',
    topic: 'Mechanics',
    questionText: 'What is kinetic energy?',
    choices: JSON.stringify(['½mv²', 'mgh', 'Fv', 'Work/time']),
    answer: '½mv²',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Physics',
    topic: 'Thermodynamics',
    questionText: 'What is the SI unit of energy?',
    choices: JSON.stringify(['Watt', 'Joule', 'Newton', 'Pascal']),
    answer: 'Joule',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Waves',
    questionText: 'What is the wavelength of a wave with frequency 10 Hz and speed 20 m/s?',
    choices: JSON.stringify(['2 m', '0.5 m', '200 m', '10 m']),
    answer: '2 m',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Physics',
    topic: 'Electricity',
    questionText: "Ohm's law states:",
    choices: JSON.stringify(['V = IR', 'V = I/R', 'R = I/V', 'I = VR']),
    answer: 'V = IR',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Mechanics',
    questionText: 'What is the SI unit of work?',
    choices: JSON.stringify(['Newton', 'Watt', 'Joule', 'Pascal']),
    answer: 'Joule',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Optics',
    questionText: 'What is the refractive index of air approximately?',
    choices: JSON.stringify(['0.33', '1', '1.33', '1.5']),
    answer: '1',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Physics',
    topic: 'Mechanics',
    questionText: 'What is pressure?',
    choices: JSON.stringify([
      'Force per area',
      'Force per time',
      'Energy per time',
      'Work per area',
    ]),
    answer: 'Force per area',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Physics',
    topic: 'Waves',
    questionText: 'What is the SI unit of wavelength?',
    choices: JSON.stringify(['Hz', 'rad/s', 'meter', 's']),
    answer: 'meter',
    year: 2022,
    difficulty: 'easy',
  },
];

// 20 CHEMISTRY questions
const chemistryQuestions = [
  {
    subject: 'Chemistry',
    topic: 'Inorganic',
    questionText: 'Which gas is produced when zinc reacts with hydrochloric acid?',
    choices: JSON.stringify(['Oxygen', 'Hydrogen', 'Nitrogen', 'Chlorine']),
    answer: 'Hydrogen',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Inorganic',
    questionText: 'What is the chemical symbol for gold?',
    choices: JSON.stringify(['Go', 'Gd', 'Au', 'Ag']),
    answer: 'Au',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic',
    questionText: 'What is the general formula for alkanes?',
    choices: JSON.stringify(['CnH2n', 'CnH(2n+2)', 'CnH(2n-2)', 'CnHn']),
    answer: 'CnH(2n+2)',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Chemistry',
    topic: 'Inorganic',
    questionText: 'What is the pH of a neutral solution?',
    choices: JSON.stringify(['0', '7', '14', '1']),
    answer: '7',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Physical',
    questionText: 'What is the SI unit of concentration?',
    choices: JSON.stringify(['g/L', 'mol/L', 'M', 'mg/mL']),
    answer: 'mol/L',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Chemistry',
    topic: 'Inorganic',
    questionText: 'Which element has atomic number 6?',
    choices: JSON.stringify(['Nitrogen', 'Carbon', 'Oxygen', 'Silicon']),
    answer: 'Carbon',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic',
    questionText: 'What is the functional group in an alcohol?',
    choices: JSON.stringify(['-CHO', '-OH', '-COOH', '-NH2']),
    answer: '-OH',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Physical',
    questionText: "What is Avogadro's number?",
    choices: JSON.stringify(['6.02 × 10²²', '6.02 × 10²³', '6.02 × 10²⁴', '6.02 × 10²¹']),
    answer: '6.02 × 10²³',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Chemistry',
    topic: 'Inorganic',
    questionText: 'What is the chemical symbol for silver?',
    choices: JSON.stringify(['Si', 'Ag', 'S', 'Se']),
    answer: 'Ag',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic',
    questionText: 'What is the functional group in a carboxylic acid?',
    choices: JSON.stringify(['-CHO', '-OH', '-COOH', '-NH2']),
    answer: '-COOH',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Physical',
    questionText: 'What is molarity?',
    choices: JSON.stringify([
      'moles of solvent',
      'moles of solute per liter',
      'mass per liter',
      'atoms per liter',
    ]),
    answer: 'moles of solute per liter',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Chemistry',
    topic: 'Inorganic',
    questionText: 'Which metal is the most reactive?',
    choices: JSON.stringify(['Iron', 'Sodium', 'Copper', 'Silver']),
    answer: 'Sodium',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic',
    questionText: 'What is the functional group in an aldehyde?',
    choices: JSON.stringify(['-CHO', '-OH', '-COOH', '-NH2']),
    answer: '-CHO',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Physical',
    questionText: 'What is the molar mass of water?',
    choices: JSON.stringify(['16 g/mol', '18 g/mol', '32 g/mol', '17 g/mol']),
    answer: '18 g/mol',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Inorganic',
    questionText: 'What does an indicator show in titration?',
    choices: JSON.stringify([
      'Amount of solute',
      'End point of reaction',
      'Temperature change',
      'pH continuously',
    ]),
    answer: 'End point of reaction',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic',
    questionText: "What is benzene's molecular formula?",
    choices: JSON.stringify(['C5H6', 'C6H6', 'C6H5', 'C7H7']),
    answer: 'C6H6',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Physical',
    questionText: 'What is a redox reaction?',
    choices: JSON.stringify([
      'Acid-base reaction',
      'Combustion only',
      'Transfer of electrons',
      'Addition reaction',
    ]),
    answer: 'Transfer of electrons',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Chemistry',
    topic: 'Inorganic',
    questionText: 'What is the valency of oxygen?',
    choices: JSON.stringify(['1', '2', '3', '4']),
    answer: '2',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Organic',
    questionText: 'What is the functional group in an amine?',
    choices: JSON.stringify(['-CHO', '-OH', '-COOH', '-NH2']),
    answer: '-NH2',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    topic: 'Physical',
    questionText: 'What is the SI unit of molar mass?',
    choices: JSON.stringify(['g', 'g/mol', 'kg/mol', 'mg']),
    answer: 'g/mol',
    year: 2022,
    difficulty: 'easy',
  },
];

// 20 BIOLOGY questions
const biologyQuestions = [
  {
    subject: 'Biology',
    topic: 'Botany',
    questionText: 'Which part of the plant makes food?',
    choices: JSON.stringify(['Root', 'Stem', 'Leaf', 'Flower']),
    answer: 'Leaf',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Anatomy',
    questionText: 'How many chambers does the human heart have?',
    choices: JSON.stringify(['2', '3', '4', '5']),
    answer: '4',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    questionText: 'What is the basic unit of heredity?',
    choices: JSON.stringify(['Chromosome', 'Gene', 'DNA', 'Protein']),
    answer: 'Gene',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    questionText: 'What is photosynthesis?',
    choices: JSON.stringify([
      'Breakdown of food',
      'Making food using sunlight',
      'Respiration',
      'Reproduction',
    ]),
    answer: 'Making food using sunlight',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Anatomy',
    questionText: 'How many bones are in the adult human body?',
    choices: JSON.stringify(['186', '206', '256', '306']),
    answer: '206',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    questionText: 'What does DNA stand for?',
    choices: JSON.stringify([
      'Deoxyribose Nucleic Acid',
      'Deoxyribonucleic Acid',
      'Digital Nucleic Acid',
      'Diribonucleic Acid',
    ]),
    answer: 'Deoxyribonucleic Acid',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Cell',
    questionText: 'What is the powerhouse of the cell?',
    choices: JSON.stringify(['Nucleus', 'Mitochondria', 'Ribosome', 'Chloroplast']),
    answer: 'Mitochondria',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    questionText: 'What is respiration?',
    choices: JSON.stringify(['Making food', 'Breathing', 'Release of energy', 'Photosynthesis']),
    answer: 'Release of energy',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Anatomy',
    questionText: 'How many chromosomes do humans have?',
    choices: JSON.stringify(['23', '46', '48', '52']),
    answer: '46',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Biology',
    topic: 'Botany',
    questionText: 'What is the male part of a flower?',
    choices: JSON.stringify(['Sepal', 'Petal', 'Stamen', 'Pistil']),
    answer: 'Stamen',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Cell',
    questionText: 'What controls cell activities?',
    choices: JSON.stringify(['Cell wall', 'Nucleus', 'Cytoplasm', 'Ribosome']),
    answer: 'Nucleus',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    questionText: 'What is a food chain?',
    choices: JSON.stringify([
      'Chain of foods',
      'Sequence of feeding',
      'Cooking process',
      'Food storage',
    ]),
    answer: 'Sequence of feeding',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Anatomy',
    questionText: 'What is the main organ of the nervous system?',
    choices: JSON.stringify(['Heart', 'Brain', 'Liver', 'Lung']),
    answer: 'Brain',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    questionText: 'What is a mutation?',
    choices: JSON.stringify(['Genetic change', 'Evolution', 'Selection', 'Adaptation']),
    answer: 'Genetic change',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Biology',
    topic: 'Botany',
    questionText: 'What is the female part of a flower?',
    choices: JSON.stringify(['Sepal', 'Petal', 'Stamen', 'Pistil']),
    answer: 'Pistil',
    year: 2023,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Cell',
    questionText: 'What does the cell wall do?',
    choices: JSON.stringify(['Produces energy', 'Provides structure', 'Stores food', 'Reproduces']),
    answer: 'Provides structure',
    year: 2022,
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    questionText: 'What is an ecosystem?',
    choices: JSON.stringify([
      'A species',
      'An organism',
      'Community and environment',
      'Population only',
    ]),
    answer: 'Community and environment',
    year: 2023,
    difficulty: 'medium',
  },
  {
    subject: 'Biology',
    topic: 'Anatomy',
    questionText: 'What is the main function of the liver?',
    choices: JSON.stringify(['Breathing', 'Digestion', 'Detoxification', 'Movement']),
    answer: 'Detoxification',
    year: 2022,
    difficulty: 'medium',
  },
  {
    subject: 'Biology',
    topic: 'Genetics',
    questionText: 'What is the process of DNA copying?',
    choices: JSON.stringify(['Transcription', 'Replication', 'Translation', 'Mitosis']),
    answer: 'Replication',
    year: 2023,
    difficulty: 'hard',
  },
  {
    subject: 'Biology',
    topic: 'Ecology',
    questionText: 'What is biodiversity?',
    choices: JSON.stringify(['Single species', 'Variety of life', 'Fossil record', 'Evolution']),
    answer: 'Variety of life',
    year: 2022,
    difficulty: 'easy',
  },
];

// Create bulk questions array for seeding
const allQuestions = [
  ...englishQuestions,
  ...mathQuestions,
  ...physicsQuestions,
  ...chemistryQuestions,
  ...biologyQuestions,
];

console.log('Starting database seeding...');

(async () => {
  try {
    // Seed subjects
    const subjectCount = await db.get('SELECT COUNT(*) as count FROM subjects');
    if (subjectCount.count === 0) {
      console.log('Seeding subjects...');
      for (const subject of subjects) {
        await db.run(
          'INSERT INTO subjects (name, code, duration, active, createdAt) VALUES (?, ?, ?, ?, ?)',
          [subject.name, subject.code, subject.duration, 1, Math.floor(Date.now() / 1000)]
        );
      }
      console.log(`✓ Inserted ${subjects.length} subjects`);
    } else {
      console.log(`Subjects already seeded (${subjectCount.count} found).`);
    }

    // Seed questions
    const questionCount = await db.get('SELECT COUNT(*) as count FROM questions');
    if (questionCount.count < 100) {
      console.log('Seeding questions...');
      for (const q of allQuestions) {
        await db.run(
          'INSERT INTO questions (subject, questionText, choices, answer, createdAt) VALUES (?, ?, ?, ?, ?)',
          [q.subject, q.questionText, q.choices, q.answer, Math.floor(Date.now() / 1000)]
        );
      }
      console.log(`✓ Inserted ${allQuestions.length} questions`);
    } else {
      console.log(`Questions already seeded (${questionCount.count} found).`);
    }

    // Seed admin user
    const adminCount = await db.get('SELECT COUNT(*) as count FROM users WHERE role = ?', [
      'admin',
    ]);
    if (adminCount.count === 0) {
      console.log('Seeding admin user...');
      const adminPassword = await bcrypt.hash('UEA@Admin2025#Secure', 10);
      await db.run(
        'INSERT INTO users (name, email, password, role, createdAt) VALUES (?, ?, ?, ?, ?)',
        [
          'Administrator',
          'admin@ultimateexamarena.com',
          adminPassword,
          'admin',
          Math.floor(Date.now() / 1000),
        ]
      );
      console.log('✓ Admin user created');
    } else {
      console.log('Admin user already exists');
    }

    const finalCount = await db.get('SELECT COUNT(*) as count FROM questions');
    console.log(`\n✅ Seeding complete! Total questions: ${finalCount.count}`);
  } catch (error) {
    console.error('Seed script error:', error);
  } finally {
    process.exit(0);
  }
})();
